### ISSUE TITLE
Error returned when searching

### ISSUE THREAD

**Issue by ovaltechnologiesinc** [nativescript-community/algolia#7]
ERROR Error: java.lang.Exception: Failed resolving constructor for class 'com.algolia.search.saas.CompletionHandler' with 0 parameters. Check the number and type of arguments.
Primitive types need to be manually wrapped in their respective Object wrappers.
If you are creating an instance of an inner class, make sure to always provide reference to the outer `this` as the first argument.

**Comment by keerl** [comment]
Can you give some example code so I can try to recreate this error?

**Comment by ovaltechnologiesinc** [comment]
I noticed the problem. I was using the Search Only Key instead of the ```Admin Key```. I changed it and it worked. Thanks
